name: concord
description: Harmony in building.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.9
  firebase_auth: ^3.3.8
  firebase_storage: ^10.2.8
  firebase_analytics: ^9.1.1
  flutter_staggered_grid_view: ^0.6.1
  transparent_image: ^2.0.0
  google_sign_in: ^5.3.0
  flutter_secure_storage: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Josefin
      fonts:
        - asset: fonts/JosefinSans-Regular.ttf
